name: Update Trackers List

on:
  schedule:
    # 每天 UTC 时间 0 点执行 (可根据需要修改)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    # VVVV  添加这个权限块以解决 403 错误  VVVV
    permissions:
      contents: write
    # ^^^^  Add this permissions block to fix the 403 error  ^^^^
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update best.txt
        run: |
          curl -sS https://cf.trackerslist.com/best.txt | sed '/^$/d' | tr '\n' ',' | sed 's/,$//' > best_processed.txt

      - name: Update all.txt
        run: |
          curl -sS https://cf.trackerslist.com/all.txt | sed '/^$/d' | tr '\n' ',' | sed 's/,$//' > all_processed.txt

      - name: Update http.txt
        run: |
          curl -sS https://cf.trackerslist.com/http.txt | sed '/^$/d' | tr '\n' ',' | sed 's/,$//' > http_processed.txt

      - name: Update nohttp.txt
        run: |
          curl -sS https://cf.trackerslist.com/nohttp.txt | sed '/^$/d' | tr '\n' ',' | sed 's/,$//' > nohttp_processed.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update tracker lists"
          file_pattern: "*.txt"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
